services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=investpolis.settings
      - DJANGO_SECRET_KEY=secret-key-here
      - DJANGO_DEBUG=0
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - sqlite_db:/app/db
    expose:
      - "8000"

volumes:
  static_volume:
  media_volume:
  sqlite_db:
