# Generated by Django 5.1.6 on 2025-02-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyfile',
            name='file_hash',
            field=models.CharField(max_length=64),
        ),
    ]
